### ISSUE TITLE
Where is the source to 0.2.0?

### ISSUE THREAD

**Issue by risicle** [wearespindle/django-ranged-fileresponse#10]
There's a 0.2.0 version on pypi, but this repo seems stuck at 0.1.2.

**Comment by m-vellinga** [comment]
This repo is for https://pypi.org/project/django-ranged-fileresponse/ which is at 0.1.2.

You probably looked at: https://pypi.org/project/django-ranged-response/ which seems to be a copy of this source code (and all the links to this repo with it) which is not mainted by us (wearespindle). (In the left navigation part at the bottom it states the maintainer as 'sih4sing5hong5')

**Comment by risicle** [comment]
_That's_ interesting - indeed I did follow the link from https://pypi.org/project/django-ranged-response/. Thankyou.
