### ISSUE TITLE
I don't want to download file instead I want to show it as text file. Is it possible?

### ISSUE THREAD

**Issue by swatipuchd** [wearespindle/django-ranged-fileresponse#8]
### Version

{version or tag here}

### File / Feature

{file or feature containing the issue}

### Expected behaviour

{what should happen}

### Actual behaviour

{what happens}

### Stacktrace / Error message

    {paste here}

### Other info

{anything else that might be related/useful}

**Comment by puittenbroek** [comment]
Yes. See also https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition for background information.

    from ranged_fileresponse import RangedFileResponse

    def some_proxy_view(request):
        filename = 'myfile.txt'
        response = RangedFileResponse(request, open(filename, 'r'), content_type='audio/wav')
        response['Content-Disposition'] = 'inline'
        return response
